feat: Added Greek language
agalwood/Motrix pull request #774
Opened 2020-08-27 15:49 UTC by Likecinema

## Description
Added Greek Language

2020-08-29 10:14 UTC, agalwood requested changes
Please adjust the code : )

2020-08-29 10:14 UTC, agalwood commented on src/shared/locales/index.js
> +    value: 'el',
Please let it be in alphabetical order

2020-08-29 12:43 UTC, Likecinema commented
Code adjusted, thanks for letting me know where the issue was :)

2020-08-30 05:16 UTC, agalwood approved these changes

2020-08-30 05:17 UTC, merged

2020-08-30 05:17 UTC, agalwood commented
Thanks