feat: Added Italian language
agalwood/Motrix pull request #794
Opened 2020-09-29 18:21 UTC by blackcat-917

## Description:
Added Italian language

## Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

2020-10-07 18:38 UTC, blackcat-917 commented
@agalwood can you review (and merge) my pull request? (Can you also opt-in Hacktoberfest for this project?)

2020-10-07 23:58 UTC, agalwood requested changes
Please adjust the code.

2020-10-07 23:58 UTC, agalwood commented on src/shared/locales/index.js
> -export const availableLanguages = [
Please keep the code indented to the original style.

2020-10-09 12:55 UTC, agalwood approved these changes

2020-10-09 12:56 UTC, merged

2020-10-09 12:56 UTC, agalwood commented
Thanks