Complete translation into Arabic
agalwood/Motrix pull request #919
Opened 2021-05-04 17:45 UTC by AhmedElTabarani

## Description
Complete translation into Arabic

## Related Issues
Complete this pull request # 833

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

2021-05-04 18:06 UTC, AhmedElTabarani commented
@agalwood  i have some question

1. spaces before functions

```js
function checkLngIsAvailable (locale)

export function getLanguage (locale = 'en-US')
``` 

I can't do `npm run dev` until put space before these function, why ? I push it with these spaces anyway

2.
After I install `node_modules` files, There is some modifies occurred on the `yarn.lock` file,  I push it also!

3.
I should not upload the package-lock.json file, right? I can delete it from this pull request

2021-05-04 19:19 UTC, AhmedElTabarani commented
What is this !!?, I don't know why the pull request has the last 14 commit !!!!
I was editing  my commit only, and did a forces push, I didn't do any things with last 14 commits.

2021-05-04 19:48 UTC, AhmedElTabarani commented
I fixed every thing, you can merge it now

2021-05-04 21:29 UTC, hadialqattan requested changes

2021-05-04 21:29 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
Here I think `حدّث`  is more precise!

2021-05-04 21:29 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
القصد أن `حدّث` فعل أمر، وهذا هو الأنسب في هذا السياق

مجرد رأي

2021-05-04 21:29 UTC, hadialqattan commented on src/shared/locales/ar/preferences.js
> +  'bt-port': 'منفذ BT للإستماع',
هنا ممكن أختلف معاك، لأن كلمة "للاستماع" همزتها همزة وصل فالأصح هو "للاستماع" إلا إذا قصدك تسهيل القراءة

2021-05-04 21:29 UTC, hadialqattan commented on src/shared/locales/ar/preferences.js
> +  'dht-port': 'منفذ DHT للإستماع',
same as above

2021-05-04 21:33 UTC, hadialqattan commented
Nice work bro @AhmedElTabarani!

2021-05-04 21:58 UTC, AhmedElTabarani commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
> القصد أن `حدّث` فعل أمر، وهذا هو الأنسب في هذا السياق

هذا صيغة سؤال فاظن ان `تحديث الآن؟` انسب 
هذا ليس فعل امر هنا

2021-05-04 22:01 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
أعتقد، `هل تريد التحديث الآن` أو `حدّث الآن` أصح والله أعلم، عموماً هو مجرد رأي لا أكثر

2021-05-04 22:02 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
لأن `تحديث الآن` ليست صيغة استفهام

2021-05-04 22:02 UTC, hadialqattan approved these changes

2021-05-04 22:04 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
If you do think you're right, please mark this as resolved!

2021-05-04 22:08 UTC, AhmedElTabarani commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
اذا نظرت للصيغة الانجليزية 
 `'update-available-message': 'A newer version of Motrix is available, update now?',`
  
  سترى انه سؤال وليس امر

2021-05-04 22:19 UTC, hadialqattan approved these changes

2021-05-04 22:20 UTC, hadialqattan approved these changes

2021-05-04 22:23 UTC, hadialqattan commented on src/shared/locales/ar/app.js
> +  'update-available-message': 'يتوفر إصدار أحدث من موتركس، تحديث الآن؟',
حتى في الإنجليزية لم يتم استخدام صيغة سؤال، ولكن في الإنجليزية هذا أمر مقبول أو على الأقل شائع، أما في العربية من الممكن أن تستفهم بصيغة الأمر أو بصيغة استفهام

2021-05-05 01:38 UTC, agalwood commented
Thank you for your translation contributions. @AhmedElTabarani @hadialqattan 

The 13 commits were made when I was developing new features. New release will coming soon : >

I think your use of force-pushed is a dangerous operation, and you should use it as little as possible or not.

2021-05-05 01:41 UTC, merged